// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/atmxlab/proxychecker/internal/details/checker (interfaces: ClientFactory)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	client "github.com/atmxlab/proxychecker/internal/details/client"
	gomock "github.com/golang/mock/gomock"
)

// MockClientFactory is a mock of ClientFactory interface.
type MockClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockClientFactoryMockRecorder
}

// MockClientFactoryMockRecorder is the mock recorder for MockClientFactory.
type MockClientFactoryMockRecorder struct {
	mock *MockClientFactory
}

// NewMockClientFactory creates a new mock instance.
func NewMockClientFactory(ctrl *gomock.Controller) *MockClientFactory {
	mock := &MockClientFactory{ctrl: ctrl}
	mock.recorder = &MockClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientFactory) EXPECT() *MockClientFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClientFactory) Create(arg0 ...client.Option) client.Client {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(client.Client)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockClientFactoryMockRecorder) Create(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClientFactory)(nil).Create), arg0...)
}
