// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/atmxlab/proxychecker/internal/details/checker (interfaces: IPApi)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ipapi "github.com/atmxlab/proxychecker/internal/details/service/ipapi"
	gomock "github.com/golang/mock/gomock"
)

// MockIPApi is a mock of IPApi interface.
type MockIPApi struct {
	ctrl     *gomock.Controller
	recorder *MockIPApiMockRecorder
}

// MockIPApiMockRecorder is the mock recorder for MockIPApi.
type MockIPApiMockRecorder struct {
	mock *MockIPApi
}

// NewMockIPApi creates a new mock instance.
func NewMockIPApi(ctrl *gomock.Controller) *MockIPApi {
	mock := &MockIPApi{ctrl: ctrl}
	mock.recorder = &MockIPApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPApi) EXPECT() *MockIPApiMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIPApi) Get(arg0 context.Context) (ipapi.Output, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(ipapi.Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIPApiMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIPApi)(nil).Get), arg0)
}
