// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/atmxlab/proxychecker/internal/details/checker (interfaces: IPApiFactory)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	checker "github.com/atmxlab/proxychecker/internal/details/checker"
	client "github.com/atmxlab/proxychecker/internal/details/client"
	gomock "github.com/golang/mock/gomock"
)

// MockIPApiFactory is a mock of IPApiFactory interface.
type MockIPApiFactory struct {
	ctrl     *gomock.Controller
	recorder *MockIPApiFactoryMockRecorder
}

// MockIPApiFactoryMockRecorder is the mock recorder for MockIPApiFactory.
type MockIPApiFactoryMockRecorder struct {
	mock *MockIPApiFactory
}

// NewMockIPApiFactory creates a new mock instance.
func NewMockIPApiFactory(ctrl *gomock.Controller) *MockIPApiFactory {
	mock := &MockIPApiFactory{ctrl: ctrl}
	mock.recorder = &MockIPApiFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPApiFactory) EXPECT() *MockIPApiFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPApiFactory) Create(arg0 client.Client) checker.IPApi {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(checker.IPApi)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIPApiFactoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPApiFactory)(nil).Create), arg0)
}
